<?php
/**
 * @file
 */

/**
 * Implements hook_block_info().
 */
function sugufi_config_block_info(){
    $blocks = array();

    $blocks['home_message_block'] = array(
        'info' => t('Home message Block'),
    );

    return $blocks;
}

function sugufi_config_block_view($delta = '') {
    $block = array();

    switch ($delta) {
        case 'home_message_block':
            $block['subject'] = '';
            $block['content'] = _block_content($delta);
            break;
    }

    return $block;
}

function _block_content($delta) {
    switch ($delta) {
        case 'home_message_block':
            $output = t('Welcome to Sugufi African Business catalogue.');
            return $output;
            break;
    }

}


/**
 * Implements hook_image_default_styles().
 */
function sugufi_config_image_default_styles(){
    $styles = array();
    $styles['business_list'] = array(
        'effects' => array(
            array(
                'name' => 'image_scale',
                'data' => array(
                    'width' => 233,
                    'upscale' => 1,
                ),
                'weight' => 0,
            ),
            array(
                'name' => 'image_crop',
                'data' => array(
                    'width' => 233,
                    'height' => 153,
                ),
                'weight' => 1,
            ),
        ),
    );

    return $styles;
}